name: Nightly Image Publish

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '4 20 * * *'
  workflow_dispatch:
    inputs:
      sha:
        description: 'Cassandra trunk commit SHA to build'
        required: false
        type: string

jobs:
  build-oss-trunk:
    strategy:
      fail-fast: false
      matrix:
        cassandra-version: ['5.0']
    runs-on: ubuntu-latest
    steps:
<<<<<<< Updated upstream
      - name: Setup Docker meta
        id: meta
=======
      - name: Setup Docker scheduled meta
        if: ${{ github.event_name == 'schedule' }}
        id: meta_schedule
>>>>>>> Stashed changes
        uses: docker/metadata-action@v4
        with:
          images: k8ssandra/cass-management-api
          flavor: |
            prefix=${{ matrix.cassandra-version }}-nightly-
          tags: |
            type=raw,value=latest
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,format=short,prefix=${{ matrix.cassandra-version }}-nightly-
<<<<<<< Updated upstream
=======
      - name: Setup Docker on demand meta
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: meta_on_demand
        uses: docker/metadata-action@v4
        with:
          images: k8ssandra/cass-management-api
          flavor: |
            prefix=${{ matrix.cassandra-version }}-
          tags: |
            type=sha,format=short,prefix=${{ matrix.cassandra-version }}-
>>>>>>> Stashed changes
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Publish ${{ matrix.cassandra-version }} to Registry
<<<<<<< Updated upstream
        id: docker_build
=======
        if: ${{ github.event_name == 'schedule' }}
        id: docker_build_schedule
>>>>>>> Stashed changes
        uses: docker/build-push-action@v3
        with:
          file: cassandra-trunk/Dockerfile.ubi8
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          target: cass-trunk
<<<<<<< Updated upstream
=======
      - name: Publish ${{ matrix.cassandra-version }} to Registry
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: docker_build_on_demand
        uses: docker/build-push-action@v3
        with:
          file: cassandra-trunk/Dockerfile.ubi8
          context: .
          push: true
          tags: ${{ steps.meta_on_demand.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          target: cass-trunk
          build-args: COMMITSHA=${{ inputs.sha }}
>>>>>>> Stashed changes
